### ISSUE TITLE
Question: About Simple but Tough-to-Beat Baseline for Sentence Embeddings

### ISSUE THREAD

**Issue by loretoparisi** [YingyuLiang/SemanticVector#1]
First of all, thanks for your work 👍 

I would like to know if there is a reference implementations i.e. by the authors - of your paper "A ["Simple but Tough-to-Beat Baseline for Sentence Embeddings" ](https://openreview.net/pdf?id=SyK00v5xx)

I'm aware of a implementation by Princeton ML [here](https://github.com/PrincetonML/SIF).

**Comment by YingyuLiang** [comment]
The Princeton ML one you found is created by us, the authors of the paper.

**Comment by loretoparisi** [comment]
@YingyuLiang I have just realized...while I was sending a PR 👍
